WIDTH = 1280
HEIGHT = 720

WIN_WIDTH = 1280
WIN_HEIGHT = 720

FPS = 15
BUFFER_SECONDS = 50
BUFFER_SIZE = FPS * BUFFER_SECONDS

MODEL_DIR = "model"
QUERY_FILE = "query.txt"

IOU_DEDUPE_THRESHOLD = 0.5
MIN_TRACK_AREA_RATIO = 0.4
DETECTION_SCORE_THRESHOLD = 0.35
